### ISSUE TITLE
Album with more than 10 discs will be added in wrong order to playlist

### ISSUE THREAD

**Issue by gjanssens** [abarisain/dmix#694]
I have MPDroid 1.07.2 (54) installed on my phone. My music collection contains several albums spanning more than 10 discs (books read and recorded).

When I add one such album to the playlist it will order the tracks as follows:
- All tracks from disc 1 (in proper disc order)
- All tracks from disc 10 (in proper disc order)
- All tracks from disc 11 (in proper disc order)
- All tracks from disc 2 (in proper disc order)
- All tracks from disc 3 (in proper disc order)
...

So discs 10 and 11 are sorted after disc 1 and before disc 2. It looks like the sorting algorithm is sorting string based instead of number based (the string "10" would sort before the string "2").

**Comment by gjanssens** [comment]
For completeness, this is with mpd version 0.16.7

**Comment by avuton** [comment]
We don't control the order things are added in. We use the ```findadd``` command in MPD, so I'd suggest filing a bug in musicpd.org/mantis. Also, before you file a bug, he will expect you to be running a modern version of MPD (I released that at the beginning of 2012!), so keep in mind this bug may not even exist anymore.

**Comment by gjanssens** [comment]
I did test against 0.18.11 and could still reproduce the issue. And I did file a bug report in mantis: http://bugs.musicpd.org/view.php?id=4313
I doubt I will ever again. Never have I been treated this poorly. I'm not given any room to try to express myself clearly and I was falsely accused of cheating right from the first comment.

Just so you know: findadd does mix up the order in my case. I have mentioned this on the #mpd channel a couple of days back. I'm pretty sure this has to do with the fact that my music is stored in subdirectories as follows:
AlbumX/diskY/trackZ

Due to the disk directory being in there (which are numbered disk1, disk2, ..., disk10,...) the ordering happens on the name of these directories. Since that sorting doesn't happen numerically, the tracks are out of order. I still believe this is a bug in mpd, but you may go file it if you like. I won't bother anymore.

Possible work arounds:
* remove the diskY directories from the hierarchy and store all tracks directly under AlbumX. That can mess up track lists in other music players though
* improve the disk numbering to be disk01, disk02, ..., disk10,...

I'm just adding the information here in case other mpdroid users run into this.

And let me take this opportunity to thank you for your kind user treatment. It's much appreciated.

**Comment by kingosticks** [comment]
Please don't stop filing bugs and reporting issues in other projects. It is
appreciated. The mpd maintainers are special, and not in a good way.

**Comment by hurzl** [comment]
:grinning:  it's really impossible to discuss anything with that 'cirrus' guy
